# Generated by Django 5.1.4 on 2025-01-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='filemanage.folder'),
        ),
        migrations.AlterModelTable(
            name='files',
            table='files',
        ),
        migrations.AlterModelTable(
            name='folder',
            table='folder',
        ),
    ]
