# Generated by Django 5.1.4 on 2025-01-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanage', '0002_alter_files_folder_alter_files_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='url',
            field=models.URLField(default='default_name'),
            preserve_default=False,
        ),
    ]
