# Generated by Django 5.1.4 on 2025-01-09 23:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanage', '0003_files_name_files_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='updated_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='files',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
